### ISSUE TITLE
Fail on errors

### ISSUE THREAD

**Issue by johnjbarton** [jankeromnes/cr#4]
When I run 

cr update 

on a dirty repo the script says

Cannot rebase: You have unstaged changes.
Please commit or stash them.

but continues anyway. Thus I don't learn about the the problem until I notice that my source is not actually up to date.

Better to bail or pre-check for unstaged changes.

**Comment by jankeromnes** [comment]
Thank you for the clean working tree check, it solves the issue when `src/` is not clean. However, my internet connection didn't allow me to check what happens when there is a separate `third_party/WebKit/` repo with unstaged changes. It probably fails with a message, but does the rest of the script continue after the failure?

**Comment by jankeromnes** [comment]
Should be fixed by now :)
